name: Build (Linux, Python3+)

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    strategy:
      matrix: 
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run Unittests
        run: nose2
      - name: Create success badge
        if: ${{ success() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_ACCESS_TOKEN }}
          gistId: 556c4aad656a0203c20c136e23700915
          filename: build-${{ matrix.platform }}-py${{ matrix.python-version }}.json
          label: build [${{ matrix.platform }}, py${{ matrix.python-version }}]
          message: passing
          color: green
      - name: Create fail badge
        if: ${{ failure() }}
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_ACCESS_TOKEN }}
          gistId: 556c4aad656a0203c20c136e23700915
          filename: build-${{ matrix.platform }}-py${{ matrix.python-version }}.json
          label: build [${{ matrix.platform }}, py${{ matrix.python-version }}]
          message: failing
          color: red