name: Build (Linux, Python3.5)

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.5
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run Unittests
        run: nose2